server:
  port: 8080

spring:
  application:
    name: gamesreview
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/reviewing?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: