server:
  port: 8080
spring:
  application:
    name: reviewing
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#  jmx:
#    enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reviewing?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: